### PR TITLE
Interaction event updates

### PR DESCRIPTION
**Pull request by fiezt1492**
Hope these might help!

### CODE REVIEW

**Review by NamVr — CHANGES_REQUESTED** [review]
`./events/contextInteraction.js` has 2 errors.
- 1 documentation error:
```diff
- import('discord.js').ContextMenuInteraction
+ import('discord.js').ContextMenuCommandInteraction
``` 

- 1 critical error
```(alias) enum ApplicationCommandType
import ApplicationCommandType
[https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

This condition will always return 'true' since the types 'ApplicationCommandType.Message' and 'ApplicationCommandType.User' have no overlap.ts(2367)```

**Comment by NamVr** [comment]
@fiezt1492 Please fix these 2 errors asap & I'll be happy to merge them into #17!

**Comment by fiezt1492** [comment]
> `./events/contextInteraction.js` has 2 errors.
> 
> * 1 documentation error:
> 
> ```diff
> - import('discord.js').ContextMenuInteraction
> + import('discord.js').ContextMenuCommandInteraction
> ```
> 
> * 1 critical error
> 
> ```ts
> (alias) enum ApplicationCommandType
> import ApplicationCommandType
> [https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
> 
> This condition will always return 'true' since the types 'ApplicationCommandType.Message' and 'ApplicationCommandType.User' have no overlap.ts(2367)
> ```

I fixed it. So sorry :P

**Comment by NamVr** [comment]
@fiezt1492 Please fix asap.

**Comment by fiezt1492** [comment]
> @fiezt1492 Please fix asap.

Sorry I've not check document. Is everything okay now?

**Review by NamVr — APPROVED** [review]
All good now

**Comment by NamVr** [comment]
Thank you @fiezt1492

**Pull request merged**
