### PR TITLE
Fixed minor comment of application rest put. Autocomplete interaction.

### PR DESCRIPTION
**Pull request by fiezt1492**

### CODE REVIEW

**Comment by NamVr** [comment]
I'll check this in some time!

**Review by NamVr — CHANGES_REQUESTED** [review]
Auto complete interactions were not added in the handler because they are just optional, but I think there's no harm adding it now.
However, auto complete interaction is not same as slash commands, and they will need their whole structure to be done like others (buttons, slash etc) folderwise (categories).
Currently, it is incomplete.

**Comment by NamVr** [comment]
Also, https://discord-api-types.dev/api/discord-api-types-v9#Routes I don't see a problem using the current method, the method exists and work in all templates

**Comment by NamVr** [comment]
Alright, it seems that discord.js itself is updated to v14 (just read the news)
So I have started work on it straightaway in #17, I hope you understand that updating v13 code is not necessary to do now, of course I will include the auto complete handler in that update!

**Comment by fiezt1492** [comment]
> Also, https://discord-api-types.dev/api/discord-api-types-v9#Routes I don't see a problem using the current method, the method exists and work in all template

You should look through the bot.js file in the rest application command post. Its just a miss spell of that method. 

```
[x] Routes.applicationGuildCommands(client_id)
[v] Routes.applicationCommands(client_id)
```
When uncomment this line to deploy global application, it went wrong and throw an error (ofcourse because its GuildCommands and its missing test_guild_id)

**Comment by NamVr** [comment]
I have corrected it in #17, have a look - and of course, thank you!

**Pull request closed without merging**
