### PR TITLE
✔ v3.0.2 | Typings, More documentations (jsdoc) + much more.

### PR DESCRIPTION
**Pull request by NamVr**
Working on,

- [ ] typings
- [ ] extended client class
- [ ] few other bug fixes

You can let me know in this pull request if you need more features!

### CODE REVIEW

**Comment by LightningBolt62** [comment]
Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.

**Comment by NamVr** [comment]
> Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.

Hey do you mean Slash Commands Manager? Sure I would like to work upon it, if you are interested you can contribute.

**Comment by NamVr** [comment]
> Feature Request: Instead of just listing all the commands in the help command, Sort the commands by categories. Like Fun commands, Mod Commands, Misc Commands etc.
> 
> Example: Example feature requested for the help command
> 
> PS: The help command this [bot](https://top.gg/bot/808708515333013565) in the screenshot uses can be found in [gtagamermods/Djs-Moderation-Bot](https://github.com/gtagamermods/Djs-Moderation-Bot/), If that helps. I used that as a starting template (even if it definitely _dosen't_ look like it should be called a template) for my bot a few months ago.

This one is really too easy, trust me. I am gonna make a guide on it instead of making it inside the template, to keep template clean for beginners and for advanced bots, they can learn from guide and do it (step by step) :)

**Comment by LightningBolt62** [comment]
> > Feature Request: Instead of just listing all the commands in the help command, Sort the commands by categories. Like Fun commands, Mod Commands, Misc Commands etc.
> > Example: Example feature requested for the help command
> > PS: The help command this [bot](https://top.gg/bot/808708515333013565) in the screenshot uses can be found in [gtagamermods/Djs-Moderation-Bot](https://github.com/gtagamermods/Djs-Moderation-Bot/), If that helps. I used that as a starting template (even if it definitely _dosen't_ look like it should be called a template) for my bot a few months ago.
> 
> This one is really too easy, trust me. I am gonna make a guide on it instead of making it inside the template, to keep template clean for beginners and for advanced bots, they can learn from guide and do it (step by step) :)

Okay then, Thanks!

**Comment by LightningBolt62** [comment]
> > Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.
> 
> Hey do you mean Slash Commands Manager? Sure I would like to work upon it, if you are interested you can contribute.

Ty!

**Comment by NamVr** [comment]
@LightningBolt62 
Yeah, the guide is available to see. I have done few pages as well.
You can join discord server as well :p
https://discord.gg/XtUG8t5FN9
https://djs.docs.namanvrati.cf

**Comment by LightningBolt62** [comment]
> @LightningBolt62 Yeah, the guide is available to see. I have done few pages as well. https://djs.docs.namanvrati.cf

Awesome

>
>You can join discord server as well :p https://discord.gg/XtUG8t5FN9 

Definitely joining!

**Comment by LightningBolt62** [comment]
> > Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.
> 
> Hey do you mean Slash Commands Manager? Sure I would like to work upon it, if you are interested you can contribute.

Can you also throw in a Context Manager too, please?

**Comment by NamVr** [comment]
> > > Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.
> > 
> > 
> > Hey do you mean Slash Commands Manager? Sure I would like to work upon it, if you are interested you can contribute.
> 
> Can you also throw in a Context Manager too, please?

It could actually be an Interaction Manager instead, since both are interaction based and are similar.

**Comment by LightningBolt62** [comment]
> > > > Feature Request: A function that automatically deletes a slash command when it gets triggered but the bot can't find that command.
> > > 
> > > 
> > > Hey do you mean Slash Commands Manager? Sure I would like to work upon it, if you are interested you can contribute.
> > 
> > 
> > Can you also throw in a Context Manager too, please?
> 
> It could actually be an Interaction Manager instead, since both are interaction based and are similar.

That's a good idea

**Comment by NamVr** [comment]
I need help lol, too much work to do

**Comment by NamVr** [comment]
Postponed this PR till further notice.

**Pull request closed without merging**
