### PR TITLE
Better help slash command + some other improvements

### PR DESCRIPTION
**Pull request by GoudronViande24**
See #11 

See commits for more details, but here is the summary:
- Improve the `help` slash command so users can get help on a single command
- Update Discord.js to latest version
- Add the LICENSE file with detailed license and so the link in readme is no longer broken
- Update some dependencies for security (audits)

I did some testing so it should be safe to implement this.

Happy to contribute to this project, it helped me a lot to learn about the new stuff of Discord.js v13!

### CODE REVIEW

**Comment by NamVr** [comment]
Hey can you reverse the license changes? I thought I did the license stuff good earlier

**Comment by NamVr** [comment]
Overall it looks good. Just the license commit I felt unnecessary. Thank you so much for the contribution.

**Comment by GoudronViande24** [comment]
I did not change the license, only made it clearer. You say in the readme that it's licensed under ISC, but you did not have the license file. I just added the file. Without it, it's like if the project was not open source and people are not allowed to use it...

**Comment by NamVr** [comment]
Oh, alright thanks for PR I'll make a little change and merge it.

**Comment by NamVr** [comment]
@GoudronViande24 I need access to contribute to the PR.

**Comment by NamVr** [comment]
Hi?

**Comment by Mioultigaming** [comment]
Problem fix ?

**Comment by GoudronViande24** [comment]
Sorry, I did not get the notification 2 days ago.

I give you access right now.

**Comment by GoudronViande24** [comment]
What changes did you want to make?

**Comment by Mioultigaming** [comment]
#12 <- **`Can anyone help me with this problem please?`** -> #12

**Comment by NamVr** [comment]
> Sorry, I did not get the notification 2 days ago.
> 
> I give you access right now.

I still don't have access

**Comment by GoudronViande24** [comment]
> > Sorry, I did not get the notification 2 days ago.
> > 
> > I give you access right now.
> 
> I still don't have access

I gave rights to all maintainers of this repo

If you can't make a commit, just make a pr to my fork it also works.

**Comment by GoudronViande24** [comment]
Any updates about this? @NamVr

**Comment by NamVr** [comment]
Today for sure, sorry for the delays.

**Comment by NamVr** [comment]
Thank you so much @GoudronViande24! If you would like to stay in touch with me, please add me on discord @ `allroundernaman#3915` or https://discord.gg/N7AJFYf8EP (Support Server). :heart:

**Comment by GoudronViande24** [comment]
Wait I just saw you merged only one commit. You should merge the entire pull request since there are some other improvements.

**Comment by GoudronViande24** [comment]
I will make another pull request so it's easier for you

**Pull request merged**
